#!/bin/sh

set -e

# make note of 'setup' directory
SETUPDIR=$(pwd)

create_directories() {
  # you need the || true because the set -e option aborts the script if any
  # command returns anything other than 0.
  if [ ! -d "$HOME/.local/bin" ]; then
    mkdir "$HOME/.local" || true
    mkdir "$HOME/.local/bin" || true
  fi
}

make_symbolic_links() {
  ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
  ln -sf "$PWD/.profile" "$HOME/.profile"
  ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
  ln -sf "$PWD/scripts" "$HOME/.local/bin/"
}

# move into each directory and execute the setup script inside
run_config_scripts() {
  for i in vim lynx newsboat; do
    cd $i && ./setup
    cd -
  done
}

create_directories
make_symbolic_links
run_config_scripts
