#!/bin/sh
# Change the shebang line of a script to match the operating system.

OS=$(uname)
SCRIPT=${1}
pwd
echo ${SCRIPT}
sed '1s|/usr/bin/|/usr/local/bin/|' ${SCRIPT} > csb.tmp

csb.tmp > ${SCRIPT}
