#!/bin/sh
# This is a multicall shell script. It is meant to be run from a symlink.
# The function executed depends on the name of the symlink used to run
# this script.

c_func() {
  printf "\e[H\e[2J"
}

p_func() {
  echo "${PWD}"
}

dgrep_func() {
  ls "${1}" | grep -i "${2}"
}

CALL_NAME=$(basename $0)
case ${CALL_NAME} in
  test-c)
    c_func
    ;;
  test-p)
    p_func
    ;;
  test-dgrep)
    dgrep_func "$@"
    ;;
  *)
    echo "USAGE"
    ;;
esac
