#!/bin/sh
# This is a multicall shell script. It is meant to be run from a symlink.
# The function executed depends on the name of the symlink used to run
# this script.

c_func() {
  printf "\e[H\e[2J"
}

p_func() {
  echo "${PWD}"
}

dgrep_func() {
  ls "${1}" | grep -i "${2}"
}

CALL_NAME=$(basename $0)
case ${CALL_NAME} in
  test-c)
    c_func
    ;;
  test-p)
    p_func
    ;;
  test-dgrep)
    dgrep_func "$@"
    ;;
  *)
    echo "USAGE:"
    echo "--------------------------------------------------------------------------------"
    echo "  Call this script using symlinks. The name of the symlink is used to call the"
    echo "  function in the script."
    echo "  Command line arguments are passed through to the underlying functions."
    echo "  If a symlink is not recognized then this usage message will be displayed."
    echo "--------------------------------------------------------------------------------"
    ;;
esac
